### ISSUE TITLE
Is there a way of custom fallback merge method?

### ISSUE THREAD

**Issue by asmodai1985** [akaunting/laravel-setting#83]

**Comment by asmodai1985** [comment]
I think it is not a good idea change the fallback behavior by default with a broken way after 1.2.2, make it as a optional setting is better

**Comment by asmodai1985** [comment]
https://github.com/akaunting/laravel-setting/commit/8768c0d5c19cc9eb4ccf343988b56cc859af3c1f

**Comment by denisdulici** [comment]
Unfortunately, that's not possible.
