### ISSUE TITLE
Facade and alias not registered .

### ISSUE THREAD

**Issue by Omar-Ess** [akaunting/laravel-setting#84]
in laravel 8 . Facade and alias are not registered automatically.  you'll have to do it manually .  and even tho , the php resolver ext does not recognize the facade nor the alias

**Comment by denisdulici** [comment]
That is done automatically via composer.

**Comment by Omar-Ess** [comment]
yeah it's supposed to . but it's not

**Comment by Omar-Ess** [comment]
i have to give an alias in the controller because the alias is not recognizable by vs code nor the helper method

**Comment by shankhadevpadam** [comment]
```php
use Akaunting\Setting\Facade as Setting;
```
