### ISSUE TITLE
after one row updated, all rows updated and the rows that have null value deleted by set method

### ISSUE THREAD

**Issue by sajadshouli** [akaunting/laravel-setting#85]
akaunting/laravel-setting : 1.2

I update one rows and the setting(["key" => 'value']) destroy my setting table because there are some fields that have NULL value

value was not nullable in migration but I need nullable value so I sat that to be null

![image](https://user-images.githubusercontent.com/80545265/115182804-db314800-a0ef-11eb-9b15-5232344fee72.png)

**Comment by denisdulici** [comment]
The package loads all the current data by default and use them in the save method. You should not change this structure.
