### ISSUE TITLE
setting update does not work at commands

### ISSUE THREAD

**Issue by sajadshouli** [akaunting/laravel-setting#86]
I have some artisan commands like update price every 10 minutes and 

```
setting(["price" => "2555"]);
Setting::set("price" , "2555");
```

do not work at all but at the controllers, middlewares,.... its fine

**Comment by denisdulici** [comment]
There is nothing special for commands and it works fine for [Akaunting](https://github.com/akaunting/akaunting/blob/master/app/Console/Commands/InvoiceReminder.php#L60) software.
