### ISSUE TITLE
Question/Help: How to get and save values for users and app settings

### ISSUE THREAD

**Issue by rabol** [akaunting/laravel-setting#87]
Hi

I'm trying to use the package to store app and user specific settings, so therefor i utilize the 'extra column' feature, but... I seem to miss something.

The below only save the last value - I have autosave set to true in the config.

```
        setting()->setExtraColumns([ 'is_system' => 1]);
        setting()->set('default.currency', 'EUR');
        setting()->set('test', 20);

        setting()->setExtraColumns([ 'is_system' => 0]);
        setting()->set('default.currency', 'EUR');
        setting()->set('test', 10);

``` 

This saves the values correctly

```
        setting()->setExtraColumns([ 'is_system' => 1]);
        setting()->set('default.currency', 'EUR');
        setting()->set('test', 20);
        setting()->save();

        setting()->setExtraColumns([ 'is_system' => 0]);
        setting()->set('default.currency', 'EUR');
        setting()->set('test', 10);
        setting()->save();
```

in the config I have 
```
    'fallback' => [
        'is_system' => 0
    ],
```

but that does not seem to have any effect on set() or get()

do I really need to call the setExtraColumns() every time I need a setting ?

**Comment by denisdulici** [comment]
Yes, you should call the `setExtraColumns()` every time you need settings. As for the autosave, it doesn't save when you call `set` method but once per runtime/request.
