### ISSUE TITLE
have bug in tenants database

### ISSUE THREAD

**Issue by webactor724** [akaunting/laravel-setting#88]
hi , i use this package in https://tenancyforlaravel.com/ , i use solution one database for each use but one app for all user , but have bug in table setting.

i have central database
for main domain 
then each tenant have self database , for this databases have setting table , but in tenant setting functions run in central database while should in tenant database.

**Comment by vahidalvandi** [comment]
because for db connection use DB facide , if we change db driver to model eloquent solve this probleam

**Comment by uyab** [comment]
@vahidalvandi I don't get it. Does this package support Eloquent driver?

**Comment by vahidalvandi** [comment]
yes please change connection from DB to model

**Comment by uyab** [comment]
Sorry, it doesn't provide "model" option:
![image](https://user-images.githubusercontent.com/149716/122368521-9d359080-cf87-11eb-9b50-d2f0ca6a5c56.png)

**Comment by vahidalvandi** [comment]
eloquent model  `model::create();`   instant `DB::INSERT (); `

**Comment by rubensrocha** [comment]
> yes please change connection from DB to model

Can you be more clear? Where exactly should I modify this?

**Comment by vahidalvandi** [comment]
just use models

**Comment by rubensrocha** [comment]
I tried to create a driver that used Eloquent (duplicated from Driver Database) and created a model Setting, but I was not successful. So I decided to make it simple, and created a model Setting and a Helper for the Tenants.
