### ISSUE TITLE
Method forgetAll() isn't working

### ISSUE THREAD

**Issue by rubensrocha** [akaunting/laravel-setting#89]
The fields are saved correctly, but when I leave an optional (nullable) field empty, the value of this field remains the same value as it was before, it is not removed or set to null(mainly with checkboxes). 

Laravel 8.49.0
Laravel-setting 1.2.7 (tested with Json and Database Drivers)
PHP 7.4.20

```
public function update(SettingRequest $request){
  $filled = array_filter($request->except('_method', '_token'));
  Setting::forgetAll();
  Setting::set($filled);
  Setting::save();
}
```

**Comment by denisdulici** [comment]
It works fine for [Akaunting](https://github.com/akaunting/akaunting/blob/master/app/Models/Common/Company.php#L498).
