### ISSUE TITLE
What’s the best way to handle multi value settings?

### ISSUE THREAD

**Issue by elfeffe** [akaunting/laravel-setting#93]
For example, I have multiple currencies.
How to have a setting called currencies, with multiple currencies inside?

**Comment by Khaledsb** [comment]
@elfeffe could you explain more with exemple please ?

**Comment by Khaledsb** [comment]
> For example, I have multiple currencies. How to have a setting called currencies, with multiple currencies inside?

@elfeffe could you explain more with exemple please ?

**Comment by Boudissa-Ihab** [comment]
@elfeffe you can have an array called "currencies", and you add elements to it by calling it this way :
setting('currencies.euro'), setting('currencies.dollar') etc...
For example, i have an array here called "store_infos" with different values in it.

![image](https://user-images.githubusercontent.com/81923945/206429254-28911845-2399-4a92-b2b6-bcd4b7d531ce.png)

- Updates work like this : `setting('store_infos.name', $value)`
- Blade call like this : `{{ setting('store_infos.name', $default) }}`

**Comment by Khaledsb** [comment]
@elfeffe 
![carbon (2)](https://user-images.githubusercontent.com/10439601/206445946-49251af8-6307-43e6-b5ad-16b0721ee688.png)

**Comment by elfeffe** [comment]
Thank you!
